#!/usr/bin/env bash
# install.sh - AFTERMATH v1 (author: Saleh)
# One-command setup for the AFTERMATH SOC range on Linux / macOS.
# Mirrors install.ps1: Docker by default, optional Windows victim VM.
#
# Linux: uses native Docker Engine (Docker CE) - no Docker Desktop, no GUI.
# macOS: uses Colima (CLI-only Docker) if Docker isn't already present.
#
#   ./install.sh                 easy path (Linux victim container)
#   ./install.sh --windows       also build a Windows victim VM (needs Vagrant)
#   ./install.sh --no-seed       bring the lab up but don't seed the compromise
#   ./install.sh --auto          don't prompt before installing anything

source "$(dirname "$0")/scripts/lib.sh"

WANT_WIN=0; SEED=1
for a in "$@"; do case "$a" in
  --windows) WANT_WIN=1 ;;
  --no-seed) SEED=0 ;;
  --auto)    LAB_AUTO=1 ;;
  -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  *) die "unknown flag: $a" ;;
esac; done
export LAB_AUTO="${LAB_AUTO:-0}"

banner() {
  printf '\033[31m\n'
  cat <<'EOF'
     _    _____ _____ _____ ____  __  __    _  _____ _   _
    / \  |  ___|_   _| ____|  _ \|  \/  |  / \|_   _| | | |
   / _ \ | |_    | | |  _| | |_) | |\/| | / _ \ | | | |_| |
  / ___ \|  _|   | | | |___|  _ <| |  | |/ ___ \| | |  _  |
 /_/   \_\_|     |_| |_____|_| \_\_|  |_/_/   \_\_| |_| |_|
EOF
  printf '\033[90m                    you arrive once it'\''s over\033[0m\n\n'
}

banner
log_info "AFTERMATH installer ($(detect_os)) - native Docker, no GUI"

# ---- 0. Docker (auto-install, then ensure the daemon is running) ------------
log_step "0/6  Checking Docker"
os="$(detect_os)"
if ! have docker; then
  log_warn "Docker not found."
  if [[ "$LAB_AUTO" != "1" ]]; then
    read -r -p "  Install Docker now? [Y/n] " ans; [[ "$ans" =~ ^[Nn]$ ]] && die "Docker required."
  fi
  case "$os" in
    linux)
      log_step "Installing Docker Engine (official convenience script)"
      curl -fsSL https://get.docker.com | sh
      sudo systemctl enable --now docker
      # let this user run docker without sudo (takes effect next login)
      sudo usermod -aG docker "$USER" || true
      log_warn "Added you to the 'docker' group. If docker calls need sudo this run, that's why."
      ;;
    macos)
      if ! have brew; then die "Install Homebrew first (https://brew.sh), then re-run."; fi
      log_step "Installing Colima + Docker CLI (no Docker Desktop needed)"
      brew install colima docker docker-compose
      colima start
      ;;
    *) die "Unsupported OS. Install Docker manually." ;;
  esac
fi

# ensure the daemon is actually up
log_step "Waiting for the Docker engine"
tries=0
until docker info >/dev/null 2>&1; do
  # try to start it if it's installed but not running
  if [[ "$os" == "linux" ]]; then sudo systemctl start docker 2>/dev/null || true; fi
  if [[ "$os" == "macos" ]]; then colima start 2>/dev/null || true; fi
  sleep 4; tries=$((tries+1))
  (( tries > 30 )) && die "Docker engine not responding. Start it and re-run."
done
# use sudo for docker only if the group change hasn't taken effect yet
DOCKER="docker"; docker info >/dev/null 2>&1 || DOCKER="sudo docker"
log_ok "Docker is ready"

# ---- optional Windows victim disclosure ------------------------------------
if [[ "$WANT_WIN" == "1" ]]; then
  log_warn "Windows victim requested - this needs Vagrant + a hypervisor (large download)."
  have vagrant || die "Vagrant not found. Install it, or drop --windows for the easy path."
fi

# ---- 1. secrets ------------------------------------------------------------
log_step "1/6  Generating secrets (.env)"
mem_gb=$(free -g 2>/dev/null | awk '/Mem:/{print $2}' || echo 16)
heap=$([[ "${mem_gb:-16}" -lt 12 ]] && echo 1g || echo 2g)
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh - DO NOT COMMIT
ELASTIC_PASSWORD=$(gen_secret)
KIBANA_PASSWORD=$(gen_secret)
FLEET_TOKEN=
STACK_VERSION=8.14.3
ES_JAVA_OPTS=-Xms${heap} -Xmx${heap}
LAB_NETWORK=172.30.0.0/24
EOF
  log_ok ".env created"
else log_info ".env exists - reusing"; fi
load_env

# ---- 2. bring up the stack (Linux victim always) ---------------------------
log_step "2/6  Starting the lab (SIEM, WAF, proxy, sensors, attacker, victim)"
CF=(-f docker-compose.yml -f docker-compose.linux-victim.yml)
# The external Windows VM (if any) ships via a STANDALONE agent straight to the
# host, so it does NOT need anything added to the shared Fleet output here.
if [[ "$WANT_WIN" == "1" ]]; then
  export LAB_HOST_IP="${LAB_HOST_IP:-192.168.56.1}"
  log_info "Windows VM will reach the SIEM via ${LAB_HOST_IP} (override with LAB_HOST_IP=…)"
fi
# Where 9200/8220 get published. Loopback unless the Windows VM has to reach
# them, and then only on the host-only adapter it sits on - never 0.0.0.0, which
# would put Elasticsearch and Fleet on the physical LAN. Kibana and the
# vulnerable web apps are pinned to 127.0.0.1 in docker-compose.yml.
BIND_IP=$([[ "$WANT_WIN" == "1" ]] && echo "${LAB_HOST_IP}" || echo "127.0.0.1")
if grep -q '^LAB_BIND_IP=' "$ENV_FILE"; then
  sed -i.bak "s|^LAB_BIND_IP=.*|LAB_BIND_IP=${BIND_IP}|" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
else
  echo "LAB_BIND_IP=${BIND_IP}" >> "$ENV_FILE"
fi
log_info "Publishing Elasticsearch/Fleet on ${BIND_IP} only; Kibana + web apps on 127.0.0.1"
# --build so Dockerfile edits always take effect (plain up reuses stale images).
$DOCKER compose "${CF[@]}" up -d --build || die "stack failed to start"
# wait for Kibana to be truly AVAILABLE, not just answering 200 (first run is slow)
log_step "Waiting for Kibana to become AVAILABLE (first run can take 10-15 min)"
kb_start=$(date +%s); kb_max=900; spin='|/-\\'; si=0
while :; do
  level=$(curl -ksf http://localhost:5601/api/status 2>/dev/null | grep -o '"level":"[a-z]*"' | head -1 | cut -d'"' -f4)
  [ -z "$level" ] && level="no response yet"
  [ "$level" = "available" ] && break
  now=$(date +%s); el=$(( now - kb_start ))
  mm=$(printf '%02d:%02d' $(( el/60 )) $(( el%60 )))
  c=${spin:si%4:1}; si=$(( si+1 ))
  printf '  %s  %s / 15:00 elapsed   Kibana: %s          ' "$c" "$mm" "$level"
  [ "$now" -gt $(( kb_start + kb_max )) ] && { printf '
'; die "Timed out waiting for Kibana. Check '$DOCKER compose logs kibana' or re-run ./install.sh (images cached now)."; }
  sleep 3
done
printf '
'; log_ok "SIEM is up (Kibana available)"

# ---- 3. fleet token --------------------------------------------------------
log_step "3/6  Creating Fleet policy and enrollment token"
TOKEN="$(bash scripts/enroll_fleet.sh)"
[[ -n "$TOKEN" ]] || die "failed to get Fleet token"
sed -i.bak "s|^FLEET_TOKEN=.*|FLEET_TOKEN=${TOKEN}|" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
log_ok "Fleet token ready"

# ---- 4. enroll victims -----------------------------------------------------
log_step "4/6  Enrolling the Linux victim"
$DOCKER compose "${CF[@]}" exec -T linux-victim /opt/enroll.sh "$TOKEN" \
  || log_warn "linux victim enroll returned non-zero; check its logs"
log_ok "Linux victim enrolled"
if [[ "$WANT_WIN" == "1" ]]; then
  log_step "4b/6  Building + enrolling the Windows VM (long step)"
  HOST_IP="${LAB_HOST_IP:-192.168.56.1}"
  # The Windows VM enrolls into its OWN policy with host-reachable endpoints —
  # NOT the Linux victim's token.
  WIN_TOKEN="$(LAB_HOST_IP="$HOST_IP" bash scripts/win_fleet.sh || true)"
  if [[ -z "$WIN_TOKEN" ]]; then
    log_warn "Could not provision the Windows Fleet policy; skipping the VM build."
  else
    # `vagrant up` runs the provisioners ONLY when it CREATES the VM. So:
    #   * fresh build  -> 04-agent already ran and enrolled; running it again
    #     would enroll a SECOND time and strand the first enrollment as a
    #     permanently "offline" agent in Fleet on every new install;
    #   * existing VM  -> `vagrant up` did nothing, and the agent still holds a
    #     token this install has just invalidated, so it must be re-enrolled or
    #     every Windows detection reads empty.
    # Decide from the machine-id file, which must be read BEFORE `vagrant up`
    # writes it.
    (
      cd victim || exit 1
      export FLEET_TOKEN="$WIN_TOKEN" FLEET_URL="http://${HOST_IP}:8220" \
             LAB_HOST_IP="$HOST_IP" STACK_VERSION="${STACK_VERSION:-8.14.3}"
      vm_existed=0
      [ -n "$(find .vagrant/machines -name id 2>/dev/null | head -1)" ] && vm_existed=1
      vagrant up --provider "${LAB_PROVIDER:-virtualbox}" || exit 1
      if [ "$vm_existed" = 1 ]; then
        vagrant provision --provision-with 04-agent || exit 1
      fi
    ) || log_warn "Windows VM failed; the Linux lab still works"
  fi
fi

# ---- 4c. guarantee the victim policy has the System integration ------------
# It's preconfigured onto victim-policy in siem/kibana.yml, but the Windows VM's
# policy is created with sys_monitoring=true (scripts/win_fleet.sh), whose
# auto-added System integration claims the DEFAULT name 'system-1' — the same
# name the preconfigured Linux one wants. Whichever wins the race, victim-policy
# can end up with NO System integration, and then every Linux auth/sudo
# detection reads empty though the agent is healthy. Verify; add under a
# distinct name if missing so the collision can't recur.
log_step "Verifying the Linux victim policy has the System integration"
KB="http://localhost:5601"; kbh=(-s -u "elastic:${ELASTIC_PASSWORD}" -H "kbn-xsrf: true" -H "Content-Type: application/json")
have_sys="$(curl "${kbh[@]}" "$KB/api/fleet/package_policies?perPage=100" 2>/dev/null \
  | python3 -c 'import sys,json;d=json.load(sys.stdin);print(any(i.get("policy_id")=="victim-policy" and i.get("package",{}).get("name")=="system" for i in d.get("items",[])))' 2>/dev/null || echo unknown)"
if [[ "$have_sys" == "True" ]]; then
  log_ok "System integration present on the victim policy"
else
  log_warn "System integration missing from the victim policy (Fleet preconfig race) — adding it"
  sysver="$(curl "${kbh[@]}" "$KB/api/fleet/epm/packages/system" 2>/dev/null | grep -o '"version":"[^"]*"' | head -1 | cut -d'"' -f4)"
  if curl "${kbh[@]}" -X POST "$KB/api/fleet/package_policies" -d "{
      \"name\":\"system-victim\",\"policy_id\":\"victim-policy\",\"namespace\":\"default\",
      \"package\":{\"name\":\"system\",\"version\":\"${sysver}\"},
      \"inputs\":{\"system-logfile\":{\"enabled\":true,\"streams\":{
        \"system.auth\":{\"enabled\":true},\"system.syslog\":{\"enabled\":true}}},
        \"system-system/metrics\":{\"enabled\":true}}}" 2>/dev/null | grep -q '"item"'; then
    log_ok "System integration added to the victim policy"
    sleep 20   # let the agent receive the policy before we seed
  else
    log_warn "Could not add the System integration; Linux auth detections may read empty."
  fi
fi

# ---- 5. seed ---------------------------------------------------------------
if [[ "$SEED" == "1" ]]; then
  log_step "5/6  Seeding the Linux compromise (attacker container)"
  # Attacker only does Linux network attacks; it skips Windows scenarios (those
  # run on the VM via Atomic Red Team). Passing 'windows' here just makes it fail.
  if $DOCKER compose "${CF[@]}" exec -T \
       -e LAB_TARGETS=linux -e ELASTIC_PASSWORD="$ELASTIC_PASSWORD" \
       attacker /attacks/seed.sh --all; then
    log_ok "Linux telemetry seeded"
  else
    log_warn "seeding reported problems — some techniques generated no telemetry."
    log_warn "check '$DOCKER compose logs attacker' and the enroll step before hunting."
  fi
  if [[ "$WANT_WIN" == "1" ]]; then
    log_warn "Windows scenarios run ON the VM via Atomic Red Team. On a Windows host"
    log_warn "the installer seeds them automatically; from here, run on the VM:"
    log_warn "  cd victim && vagrant winrm -s powershell -c \"Invoke-AtomicTest <T> -TestNumbers <n>\""
    log_warn "Once they are seeded, validate the Windows answer key with:"
    log_warn "  $DOCKER compose ${CF[*]} exec -T -e ELASTIC_PASSWORD=\$ELASTIC_PASSWORD \\"
    log_warn "    -e LAB_TARGETS=linux,windows attacker python3 /attacks/validate_detections.py /scenarios"
  fi
else log_warn "5/6  Skipping seed (--no-seed)"; fi

# ---- 6. validate the answer key matches what we seeded ---------------------
if [[ "$SEED" == "1" ]]; then
  log_step "6/6  Validating detections (each answer-key query must return hits)"
  # ALWAYS linux-only here. This installer does not seed the Windows scenarios -
  # they run ON the VM via Atomic Red Team, which only the Windows installer
  # automates (see the note in step 5). Validating "linux,windows" would query
  # telemetry that was never created and report ~12 phantom failures, making a
  # perfectly healthy lab look broken.
  VT="linux"
  $DOCKER compose "${CF[@]}" exec -T \
    -e ELASTIC_PASSWORD="$ELASTIC_PASSWORD" -e LAB_TARGETS="$VT" \
    attacker python3 /attacks/validate_detections.py /scenarios \
    && log_ok "All detections match the seeded telemetry" \
    || log_warn "Some detections returned no hits - an answer-key query is out of sync."

  # The Security detection rules were imported at stack startup, BEFORE any
  # logs-* data existed, and run on a schedule - so they sit idle ("no matching
  # index") until their next cycle and Security > Alerts stays empty. Now that
  # the compromise is seeded, force a prompt run (disable then enable) so the
  # rules fire against the backdated telemetry.
  log_step "Triggering the detection rules against the seeded telemetry"
  kbh=(-sf -u "elastic:${ELASTIC_PASSWORD}" -H "kbn-xsrf: true" -H "Content-Type: application/json")
  BA="http://localhost:5601/api/detection_engine/rules/_bulk_action"
  if curl "${kbh[@]}" -X POST "$BA" -d '{"query":"","action":"disable"}' >/dev/null 2>&1 && sleep 2 \
     && curl "${kbh[@]}" -X POST "$BA" -d '{"query":"","action":"enable"}' >/dev/null 2>&1; then
    log_ok "Detection rules triggered - alerts populate Security > Alerts within ~1-2 min"
    log_info "  Alerts inherit the backdated event time; widen the Alerts time picker to 'Last 30 days'."
  else
    log_warn "Could not trigger the detection rules; they fire on their next 5-min cycle."
  fi
fi

# ---- summary ---------------------------------------------------------------
pass=$(grep '^ELASTIC_PASSWORD=' "$ENV_FILE" | cut -d= -f2)
echo; log_ok "Lab is ready."
cat <<EOF

  Kibana     http://localhost:5601   (user: elastic  pass: ${pass})
  Victim     container 'linux-victim'$([[ "$WANT_WIN" == 1 ]] && echo " + Windows VM (RDP localhost:53389)")
  Scenarios  see SCENARIOS.md  (answers in SOLUTIONS.md)

  Live attack:  ${DOCKER} compose exec attacker /attacks/seed.sh --live T1059.004
  Stop:         ${DOCKER} compose down
  Rebuild:      ${DOCKER} compose down -v ; ./install.sh

EOF
